//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Packeges/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""controller"",
            ""id"": ""691893af-01cf-4c49-802d-d53860aeefee"",
            ""actions"": [
                {
                    ""name"": ""movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0c124c7b-caec-4412-97f4-e8bb45f0f318"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""movement1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""96b5e6cd-840e-4d92-b294-d9d9ed6e6b36"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""f4263f49-70e5-480a-b641-ce133ce2e47e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""33f1d8d1-bdd3-45b8-ae46-95aa12a5e094"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a4065acd-5dbb-44a8-ac4c-208a5a5b7596"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireL"",
                    ""type"": ""Button"",
                    ""id"": ""171007f3-7cd1-4608-b50d-85065d4f9d3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireL1"",
                    ""type"": ""Button"",
                    ""id"": ""e0ccd9ef-63e5-4f8d-9b4b-468f8c77cedd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fireR"",
                    ""type"": ""Button"",
                    ""id"": ""dd83da28-c802-49da-9220-f17324c75d55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""54c6046d-1322-4cfc-9475-7c7bcadffaf4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""escape"",
                    ""type"": ""Button"",
                    ""id"": ""cb473851-fc46-4368-8e24-57151de6163d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e164168d-b172-43ba-9d79-8acc866ec24e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d5edad64-3abc-4d73-8587-8ed78bd56f39"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""26204f38-7232-423a-bd2a-a1b3d1d17a5e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1eb58156-e116-4aea-82be-0455500eacea"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""edff22c1-50be-446d-b0e1-37ba0e91270d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d4e944ab-66f4-4734-90bb-643910e53122"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c36f5b43-aa12-4a37-8662-8674c9cfe62c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2d56c485-7c17-4000-8d26-e0b33500ab97"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5e1530cd-8b6f-496e-91d5-f5ea9c804daf"",
                    ""path"": ""<HID::OpenChord X RMIT Exertion Games Lab UnoJoy Joystick>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ab690c1f-b22e-4247-b70d-adea5d7d4deb"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""15953303-ecf7-4dea-aab5-baed7d43c65c"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ab75542c-0581-47b3-91b8-2c40540ae898"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""33b8d934-5c2a-4a4b-aa07-7d28d79ff7b1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0f39407-c558-48f9-8465-bf097c13e331"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a58af478-2ae8-4a36-9195-22284382f95e"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95e64a67-8ae7-4a79-8548-89d222fd864c"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""157ffa2a-25b0-41eb-be62-942fd1899d78"",
                    ""path"": ""<HID::OpenChord X RMIT Exertion Games Lab UnoJoy Joystick>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29dfa759-7b6c-4d89-8d84-0c8dccb47040"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d155936c-49d2-495f-80cb-5e6cd3d5b851"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da14b9a6-8e7d-4ac7-9d85-6610d29fdc98"",
                    ""path"": ""<HID::OpenChord X RMIT Exertion Games Lab UnoJoy Joystick>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e903c026-e82d-4f38-9fa5-55351e3aa37e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbde5387-89c3-4d14-8e86-fad0d273c194"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""609e6651-11f5-4a37-926b-79105298a924"",
                    ""path"": ""<HID::OpenChord X RMIT Exertion Games Lab UnoJoy Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5362b21-11f5-4f8a-8a1c-6422ec19702b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ef871ce-caf8-4df9-b6b5-12f801210a98"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c02f63a8-b3d0-4736-938d-026e3a8224eb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee0432b6-d5aa-47b6-9f5a-42e7d27e6f1d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92fde3da-09fb-49f3-ace2-6f095b0f600d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf5b42d-bcfe-4b6d-960b-59671ccc3e83"",
                    ""path"": ""<HID::OpenChord X RMIT Exertion Games Lab UnoJoy Joystick>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0a274b11-93c8-4165-9eac-8d0d3b819905"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1b78c982-c24f-42ee-9261-f515d0161f88"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1bd8d0c1-8108-4701-aa31-959947c47104"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""187fab14-d6e0-4fb8-971a-6a136b4441d2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4cf0a705-990c-494a-9d64-b14d040dc453"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4a961370-72df-4427-9a9e-7c7ea7e7ada9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abea651d-a858-4fba-83ce-b19137de6de9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79fb56b9-3cc7-4c04-906d-96f9f4d13387"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d49b551-80d6-4037-a619-f0baee0679af"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fireL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""quit"",
            ""id"": ""12923ded-0d74-4278-85a6-3a7b39fa0fbd"",
            ""actions"": [
                {
                    ""name"": ""quit"",
                    ""type"": ""Button"",
                    ""id"": ""4ffc6dea-4865-4db5-b3fe-b15b20185c52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""56c65782-7c7d-459e-921e-0558517b6543"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // controller
        m_controller = asset.FindActionMap("controller", throwIfNotFound: true);
        m_controller_movement = m_controller.FindAction("movement", throwIfNotFound: true);
        m_controller_movement1 = m_controller.FindAction("movement1", throwIfNotFound: true);
        m_controller_jump = m_controller.FindAction("jump", throwIfNotFound: true);
        m_controller_mouseX = m_controller.FindAction("mouseX", throwIfNotFound: true);
        m_controller_mouseY = m_controller.FindAction("mouseY", throwIfNotFound: true);
        m_controller_fireL = m_controller.FindAction("fireL", throwIfNotFound: true);
        m_controller_fireL1 = m_controller.FindAction("fireL1", throwIfNotFound: true);
        m_controller_fireR = m_controller.FindAction("fireR", throwIfNotFound: true);
        m_controller_interact = m_controller.FindAction("interact", throwIfNotFound: true);
        m_controller_escape = m_controller.FindAction("escape", throwIfNotFound: true);
        // quit
        m_quit = asset.FindActionMap("quit", throwIfNotFound: true);
        m_quit_quit = m_quit.FindAction("quit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // controller
    private readonly InputActionMap m_controller;
    private List<IControllerActions> m_ControllerActionsCallbackInterfaces = new List<IControllerActions>();
    private readonly InputAction m_controller_movement;
    private readonly InputAction m_controller_movement1;
    private readonly InputAction m_controller_jump;
    private readonly InputAction m_controller_mouseX;
    private readonly InputAction m_controller_mouseY;
    private readonly InputAction m_controller_fireL;
    private readonly InputAction m_controller_fireL1;
    private readonly InputAction m_controller_fireR;
    private readonly InputAction m_controller_interact;
    private readonly InputAction m_controller_escape;
    public struct ControllerActions
    {
        private @PlayerInput m_Wrapper;
        public ControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @movement => m_Wrapper.m_controller_movement;
        public InputAction @movement1 => m_Wrapper.m_controller_movement1;
        public InputAction @jump => m_Wrapper.m_controller_jump;
        public InputAction @mouseX => m_Wrapper.m_controller_mouseX;
        public InputAction @mouseY => m_Wrapper.m_controller_mouseY;
        public InputAction @fireL => m_Wrapper.m_controller_fireL;
        public InputAction @fireL1 => m_Wrapper.m_controller_fireL1;
        public InputAction @fireR => m_Wrapper.m_controller_fireR;
        public InputAction @interact => m_Wrapper.m_controller_interact;
        public InputAction @escape => m_Wrapper.m_controller_escape;
        public InputActionMap Get() { return m_Wrapper.m_controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void AddCallbacks(IControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_ControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Add(instance);
            @movement.started += instance.OnMovement;
            @movement.performed += instance.OnMovement;
            @movement.canceled += instance.OnMovement;
            @movement1.started += instance.OnMovement1;
            @movement1.performed += instance.OnMovement1;
            @movement1.canceled += instance.OnMovement1;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @mouseX.started += instance.OnMouseX;
            @mouseX.performed += instance.OnMouseX;
            @mouseX.canceled += instance.OnMouseX;
            @mouseY.started += instance.OnMouseY;
            @mouseY.performed += instance.OnMouseY;
            @mouseY.canceled += instance.OnMouseY;
            @fireL.started += instance.OnFireL;
            @fireL.performed += instance.OnFireL;
            @fireL.canceled += instance.OnFireL;
            @fireL1.started += instance.OnFireL1;
            @fireL1.performed += instance.OnFireL1;
            @fireL1.canceled += instance.OnFireL1;
            @fireR.started += instance.OnFireR;
            @fireR.performed += instance.OnFireR;
            @fireR.canceled += instance.OnFireR;
            @interact.started += instance.OnInteract;
            @interact.performed += instance.OnInteract;
            @interact.canceled += instance.OnInteract;
            @escape.started += instance.OnEscape;
            @escape.performed += instance.OnEscape;
            @escape.canceled += instance.OnEscape;
        }

        private void UnregisterCallbacks(IControllerActions instance)
        {
            @movement.started -= instance.OnMovement;
            @movement.performed -= instance.OnMovement;
            @movement.canceled -= instance.OnMovement;
            @movement1.started -= instance.OnMovement1;
            @movement1.performed -= instance.OnMovement1;
            @movement1.canceled -= instance.OnMovement1;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @mouseX.started -= instance.OnMouseX;
            @mouseX.performed -= instance.OnMouseX;
            @mouseX.canceled -= instance.OnMouseX;
            @mouseY.started -= instance.OnMouseY;
            @mouseY.performed -= instance.OnMouseY;
            @mouseY.canceled -= instance.OnMouseY;
            @fireL.started -= instance.OnFireL;
            @fireL.performed -= instance.OnFireL;
            @fireL.canceled -= instance.OnFireL;
            @fireL1.started -= instance.OnFireL1;
            @fireL1.performed -= instance.OnFireL1;
            @fireL1.canceled -= instance.OnFireL1;
            @fireR.started -= instance.OnFireR;
            @fireR.performed -= instance.OnFireR;
            @fireR.canceled -= instance.OnFireR;
            @interact.started -= instance.OnInteract;
            @interact.performed -= instance.OnInteract;
            @interact.canceled -= instance.OnInteract;
            @escape.started -= instance.OnEscape;
            @escape.performed -= instance.OnEscape;
            @escape.canceled -= instance.OnEscape;
        }

        public void RemoveCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_ControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControllerActions @controller => new ControllerActions(this);

    // quit
    private readonly InputActionMap m_quit;
    private List<IQuitActions> m_QuitActionsCallbackInterfaces = new List<IQuitActions>();
    private readonly InputAction m_quit_quit;
    public struct QuitActions
    {
        private @PlayerInput m_Wrapper;
        public QuitActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @quit => m_Wrapper.m_quit_quit;
        public InputActionMap Get() { return m_Wrapper.m_quit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QuitActions set) { return set.Get(); }
        public void AddCallbacks(IQuitActions instance)
        {
            if (instance == null || m_Wrapper.m_QuitActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QuitActionsCallbackInterfaces.Add(instance);
            @quit.started += instance.OnQuit;
            @quit.performed += instance.OnQuit;
            @quit.canceled += instance.OnQuit;
        }

        private void UnregisterCallbacks(IQuitActions instance)
        {
            @quit.started -= instance.OnQuit;
            @quit.performed -= instance.OnQuit;
            @quit.canceled -= instance.OnQuit;
        }

        public void RemoveCallbacks(IQuitActions instance)
        {
            if (m_Wrapper.m_QuitActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQuitActions instance)
        {
            foreach (var item in m_Wrapper.m_QuitActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QuitActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QuitActions @quit => new QuitActions(this);
    public interface IControllerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMovement1(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnFireL(InputAction.CallbackContext context);
        void OnFireL1(InputAction.CallbackContext context);
        void OnFireR(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IQuitActions
    {
        void OnQuit(InputAction.CallbackContext context);
    }
}
